<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPMXGUAW0506" ignored="0" name="Test" tests="5" failures="2" timestamp="2019-11-07T15:08:34 CST" time="52.432" errors="0">
  <testcase name="feature" time="21.235" classname="com.testautomation.TestRunner.TestRunner"/>
  <testcase name="feature" time="23.44" classname="com.testautomation.TestRunner.TestRunner"/>
  <testcase name="feature" time="23.518" classname="com.testautomation.TestRunner.TestRunner"/>
  <testcase name="feature" time="51.32" classname="com.testautomation.TestRunner.TestRunner">
    <failure type="java.lang.AssertionError" message="PRUEBA FALLO ASSERT TESTNG">
      <![CDATA[java.lang.AssertionError: PRUEBA FALLO ASSERT TESTNG
at com.testautomation.Listeners.ExtentReportListener.testStepHandle(ExtentReportListener.java:55)
at com.testautomation.StepDefinitions.LoginGalenFramework.i_validate_the_another_note(LoginGalenFramework.java:112)
at ✽.I validate the another note "Segundo Mensaje"(./features/GalenPageTesting.feature:47)
... Removed 1 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="51.674" classname="com.testautomation.TestRunner.TestRunner">
    <failure type="java.lang.AssertionError" message="PRUEBA FALLO ASSERT TESTNG">
      <![CDATA[java.lang.AssertionError: PRUEBA FALLO ASSERT TESTNG
at com.testautomation.Listeners.ExtentReportListener.testStepHandle(ExtentReportListener.java:55)
at com.testautomation.StepDefinitions.LoginGalenFramework.i_validate_the_another_note(LoginGalenFramework.java:112)
at ✽.I validate the another note "Segundo Mensaje"(./features/GalenPageTesting.feature:38)
... Removed 1 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Test -->
