<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPMXGUAW0354" ignored="0" name="Test" tests="2" failures="1" timestamp="2019-10-25T23:30:14 CDT" time="12.801" errors="0">
  <testcase name="feature" time="12.127" classname="com.testautomation.TestRunner.TestRunner">
    <failure type="java.lang.AssertionError" message="No se pudo completar la validacionjava.lang.AssertionError: did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: No se pudo completar la validacionjava.lang.AssertionError: did not expect to find [true] but found [false]
at com.testautomation.StepDefinitions.LoginGalenFramework.i_validate_the_another_note(LoginGalenFramework.java:140)
at âœ½.I validate the another note "Segundo Mensaje"(./features/GalenPageTesting.feature:21)
... Removed 1 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase name="feature" time="12.333" classname="com.testautomation.TestRunner.TestRunner"/>
</testsuite> <!-- Test -->
